name: test
on: [push, pull_request]
jobs:
  test:
    name: Node 19 and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - uses: microsoft/playwright-github-action@v1
      - name: npm install
        run: npm i
      - name: npm test
        run: npm test